version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout

      - restore_cache:
          name: Restore virtualenvs from previous builds
          key: virtualenvs-dependencies-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}

      - run:
          name: Install system dependencies
          command: >
            sudo apt-get update && 
            sudo apt-get -y install \
              poppler-utils libfile-mimeinfo-perl libimage-exiftool-perl \
              ghostscript libsecret-1-0 zlib1g-dev libjpeg-dev imagemagick libmagic1 webp \
              gnumeric libreoffice

      - run:
          name: Install Poetry and project's pip packages
          command: |
            export TERM=xterm-256color
            export COLUMNS=150
            curl -sSL https://install.python-poetry.org | python3 -
            poetry install --with dev

      - save_cache:
          name: Save virtualenvs cache for future builds
          key: virtualenvs-dependencies-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs

      - run:
          name: Create a distribution and run tests
          command: |
            make dist test
