version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout

      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install system dependencies
          command: |
            sudo apt-get update && sudo apt-get install exiftool pythonmagick libfile-mimeinfo-perl gnumeric libreoffice

      - run:
          name: install pipenv package
          command: |
            pip install pipenv

      - run:
          name: install pip dependencies
          command: |
            pipenv install -d

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"

      - run:
          name: run tests
          command: |
            pipenv run nosetests