version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudp apt-get update && apt-get install exiftool libfile-mimeinfo-perl gnumeric
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install xvfbwrapper
            python setup.py develop
            pip install --upgrade pdf2image==1.7.1 git+https://github.com/algoo/preview-generator.git
            pip install -e ".[dev]"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
