version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout

      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install system dependencies
          command: >
            sudo apt-get update && 
            sudo apt-get -y install \
              poppler-utils libfile-mimeinfo-perl libimage-exiftool-perl \
              ghostscript libsecret-1-0 zlib1g-dev libjpeg-dev imagemagick libmagic1 webp \
              gnumeric libreoffice

      - run:
          name: Install pipenv package
          command: |
            pip install pipenv

      - run:
          name: Install pip dependencies
          command: |
            pipenv install -d

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            
      - run:
          name: Create a distribution and run tests
          command: |
            make dist test